apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
      
      global:
        resolve_timeout: 5m
      
      route:
        group_by: ['alertname', 'cluster']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        receiver: 'slack-notifications'
      
      receivers:
        - name: 'slack-notifications'
          slack_configs:
            - send_resolved: true
              text: "{{ .CommonAnnotations.description }}"
              title: "{{ .CommonAnnotations.summary }}"
              title_link: "https://wizfi-grafana.duckdns.org"
              color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
              api_url: 'https://hooks.slack.com/services/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'
              channel: '#alerts'
              username: 'Prometheus Alert'
              icon_emoji: ':fire:'
      
