apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wizfi-tls
  namespace: wizfi
spec:
  secretName: wizfi-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - wizfiservices.duckdns.org
    # Remove subdomains unless you have separate Ingress rules for them
  usages:
    - digital signature
    - key encipherment