apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wizfi-certs
  namespace: wizfi
spec:
  secretName: wizfi-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - wizfiservices.duckdns.org
    - auth.wizfiservices.duckdns.org
    - user.wizfiservices.duckdns.org
    - billing.wizfiservices.duckdns.org
    - payments.wizfiservices.duckdns.org
    - notify.wizfiservices.duckdns.org
    - analytics.wizfiservices.duckdns.org
    - admin.wizfiservices.duckdns.org

  usages:
    - digital signature
    - key encipherment
  duration: 2160h # 90d
  renewBefore: 360h # 15d