apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-duckdns
  template:
    metadata:
      labels:
        app: cert-manager-webhook-duckdns
    spec:
      serviceAccountName: cert-manager-webhook-duckdns
      containers:
        - name: webhook
          image: docker.io/wisdomshaibu/cert-manager-webhook-duckdns:v1.6.1
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
          env:
            - name: DUCKDNS_TOKEN
              value: "Y997f7b2c-ce52-426f-aea3-b5882e8c728f"
          ports:
            - containerPort: 443
