apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-duckdns
  template:
    metadata:
      labels:
        app: cert-manager-webhook-duckdns
    spec:
      containers:
        - name: webhook
          image: docker.io/wizshai/duckdns-webhook:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: https
          volumeMounts:
            - name: webhook-certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: webhook-certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  ports:
    - port: 443
      targetPort: https
  selector:
    app: cert-manager-webhook-duckdns
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-webhook-duckdns
webhooks:
  - name: webhook.cert-manager-webhook-duckdns.cert-manager.svc
    clientConfig:
      service:
        name: cert-manager-webhook-duckdns
        namespace: cert-manager
        path: "/mutate"
      caBundle: Cg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["cert-manager.io"]
        apiVersions: ["v1"]
        resources: ["certificates"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: duckdns.az0ne.dev
spec:
  group: az0ne.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    plural: duckdns
    singular: duckdns
    kind: DuckDNS
