apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: wizfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13.14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: wizfi_db
            - name: POSTGRES_USER
              value: wizfi_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc