apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/app-root: /frontend/login
    # Remove all rewrite rules and use exact path matching
    #nginx.ingress.kubernetes.io/rewrite-target: /
    # Simplified configuration without snippets
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          # Frontend paths - exact matches
          - path: /frontend/login
            pathType: Exact
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /frontend/health
            pathType: Exact
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          # Other service paths
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001

          - path: /billing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 3002

          - path: /payments(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 3003

          - path: /notify(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 3004

          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 3005

          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3006

  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls