apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/app-root: /frontend/login
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ ^/\.well-known/acme-challenge/ {
        default_type text/plain;
        return 200 "$1.$2";
      }
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          # ACME challenge path must come FIRST
          - path: /.well-known/acme-challenge/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-ingress-ingress-nginx-controller
                port:
                  number: 80
          
          # Frontend paths with proper rewrite
          - path: /frontend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
            # Specific rewrite for frontend paths
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          # Application paths
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /billing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 3002
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /payments(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 3003
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /notify(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 3004
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 3005
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3006
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

          # Default path (root) redirects to frontend
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2

  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls