apiVersion: networking.k8s.io/v1
kind: Ingress
meta
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # ✅ NO cert-manager annotations here
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          - path: /frontend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          # ... other paths
  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls  # Only managed by cert.yaml