apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    #nginx.ingress.kubernetes.io/app-root: /frontend/login
    nginx.ingress.kubernetes.io/use-regex: "true"
    # ✅ Add rewrite to strip /auth, /user, etc.
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # Auth: /auth/login → /login
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          # User: /user/users → /users
          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80

          # Billing
          - path: /billing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 80

          # Payments
          - path: /payments(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 80

          # Notifications
          - path: /notify(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 80

          # Analytics
          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 80

          # Admin
          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80

  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls