apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/app-root: /frontend/login
    # Explicit configuration for frontend paths
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/frontend {
        proxy_pass http://frontend-service.wizfi.svc.cluster.local:80$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Real-IP $remote_addr;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          # Frontend path - catch-all prefix
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /frontend/
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          # Other service paths
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001

          - path: /billing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 3002

          - path: /payments(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 3003

          - path: /notify(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 3004

          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 3005

          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3006

  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls