apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/app-root: /frontend/login
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ ^/\.well-known/acme-challenge/ {
        default_type text/plain;
        return 200 "$1.$2";
      }
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          # ACME challenge path must come FIRST
          - path: /.well-known/acme-challenge/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-ingress-ingress-nginx-controller
                port:
                  number: 80
          
          # Frontend paths
          - path: /frontend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # Application paths
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001

          - path: /billing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 3002

          - path: /payments(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 3003

          - path: /notify(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 3004

          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 3005

          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3006

          # Default path (root) redirects to frontend
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls