apiVersion: networking.k8s.io/v1
kind: Ingress
meta
  name: wizfi-ingress
  namespace: wizfi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Rewritten-To "/$2" always;
spec:
  ingressClassName: nginx
  rules:
    - host: wizfiservices.duckdns.org
      http:
        paths:
          # Frontend: /frontend/(.*) → /frontend/(.*)
          - path: /frontend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
<<<<<<< HEAD
=======

          # Auth: /auth/(.*) → /(.*) → /login
>>>>>>> 75f0cd05b748410b71736667fc22ee7e292d01d6
          - path: /auth/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
<<<<<<< HEAD
=======

          # User: /user/(.*) → /(.*) → /users
>>>>>>> 75f0cd05b748410b71736667fc22ee7e292d01d6
          - path: /user/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 80
<<<<<<< HEAD
=======

          # Billing
>>>>>>> 5a00f6ecc0c9410289716cd008f20c55fbe5db9c
          - path: /billing/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: billing-service
                port:
                  number: 80

          # Payments
          - path: /payments/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-service
                port:
                  number: 80

          # Notifications
          - path: /notify/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notifications-service
                port:
                  number: 80

          # Analytics
          - path: /analytics/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: analytics-service
                port:
                  number: 80

          # Admin
          - path: /admin/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-service
                port:
                  number: 80
  tls:
    - hosts:
        - wizfiservices.duckdns.org
      secretName: wizfi-tls
