apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: wizfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: wizfi/notifications-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
