apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: wizfi
spec:
  selector:
    app: notifications-service
  ports:
    - name: http
      port: 80
      targetPort: 3004