apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: wizfi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: wizfi/frontend-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3007"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              value: http://auth-service.wizfi.svc.cluster.local:3000  
            - name: ADMIN_SERVICE_URL
              value: http://admin-service.wizfi.svc.cluster.local:3006
          livenessProbe:
            httpGet:
              path: /frontend/health
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /frontend/health
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
