apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: wizfi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: wizfi/frontend-service:latest
          ports:
            - containerPort: 3007
          env:
            - name: PORT
              value: "3007"
            - name: HOST
              value: "0.0.0.0"
            - name: BASE_PATH
              value: "/frontend"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            # ✅ Use internal cluster URLs for backend APIs
            - name: AUTH_SERVICE_URL
              value: "http://auth-service"
            - name: ADMIN_SERVICE_URL
              value: "http://admin-service"
            - name: USER_SERVICE_URL
              value: "http://user-service"
            - name: BILLING_SERVICE_URL
              value: "http://billing-service"
            - name: PAYMENTS_SERVICE_URL
              value: "http://payments-service"
            - name: NOTIFICATIONS_SERVICE_URL
              value: "http://notifications-service"
            - name: ANALYTICS_SERVICE_URL
              value: "http://analytics-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: static-assets
              mountPath: /app/public
      volumes:
        - name: static-assets
          emptyDir: {}

