grafana:
  enabled: true
  adminPassword: "wizfiadmin"
  service:
    type: ClusterIP
    port: 80  # Explicitly set port 80
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-http"
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: nginx
    hosts:
      - wizfi-grafana.duckdns.org
    path: /
    tls:
      - hosts:
          - wizfi-grafana.duckdns.org
        secretName: grafana-tls