name: Deploy Auth Service

on:
  push:
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service.yml'
    branches:
      - main

env:
  DOCKER_USER: wizfi
  NAMESPACE: wizfi

jobs:
  deploy-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K3S_KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        run: |
          docker build -t $DOCKER_USER/auth-service:latest ./auth-service
          docker push $DOCKER_USER/auth-service:latest

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/auth/service.yaml
