name: Build & Push All Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '.github/workflows/deploy-images.yml'

env:
  DOCKER_USER: wizfi

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push auth-service
        run: |
          docker build -t $DOCKER_USER/auth-service:latest ./auth-service
          docker push $DOCKER_USER/auth-service:latest

      - name: Build & push user-service
        run: |
          docker build -t $DOCKER_USER/user-service:latest ./user-service
          docker push $DOCKER_USER/user-service:latest

      - name: Build & push billing-service
        run: |
          docker build -t $DOCKER_USER/billing-service:latest ./billing-service
          docker push $DOCKER_USER/billing-service:latest

      - name: Build & push payments-service
        run: |
          docker build -t $DOCKER_USER/payments-service:latest ./payments-service
          docker push $DOCKER_USER/payments-service:latest

      - name: Build & push notifications-service
        run: |
          docker build -t $DOCKER_USER/notifications-service:latest ./notifications-service
          docker push $DOCKER_USER/notifications-service:latest

      - name: Build & push analytics-service
        run: |
          docker build -t $DOCKER_USER/analytics-service:latest ./analytics-service
          docker push $DOCKER_USER/analytics-service:latest

      - name: Build & push admin-service
        run: |
          docker build -t $DOCKER_USER/admin-service:latest ./admin-service
          docker push $DOCKER_USER/admin-service:latest

      - name: Build & push frontend-service
        run: |
          docker build -t $DOCKER_USER/frontend-service:latest ./frontend-service
          docker push $DOCKER_USER/frontend-service:latest
