name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  CLUSTER_NAME: wizfi-cluster
  REGION: us-east-1
  NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $REGION \
            --name $CLUSTER_NAME

      - name: Create namespace if not exists
        run: |
          kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

      - name: Add Helm repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Apply K8s Deployments
        run: |
          kubectl apply -f k8s/ --recursive

      - name: Apply Ingress Rules
        run: |
          kubectl apply -f wizfi-ingress.yaml
