name: Deploy Frontend Service

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-service.yml'
    branches:
      - main

env:
  DOCKER_USER: wizfi
  NAMESPACE: wizfi

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t $DOCKER_USER/frontend-service:latest ./frontend
          docker push $DOCKER_USER/frontend-service:latest

      - name: Setup Kubeconfig for K3s
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Deploy to K3s
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f k8s/frontend/service.yaml
