name: Deploy Frontend Service

on:
  push:
    paths:
      - 'frontend-service/**'
      - '.github/workflows/frontend-service.yml'
    branches:
      - main

env:
  DOCKER_USER: wizfi
  NAMESPACE: wizfi

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        run: |
          docker build -t $DOCKER_USER/frontend-service:latest ./frontend-service
          docker push $DOCKER_USER/frontend-service:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/frontend/service.yaml
