name: Deploy User Service

on:
  push:
    paths:
      - 'user-service/**'
      - '.github/workflows/user-service.yml'
    branches:
      - main

env:
  DOCKER_USER: wizfi
  CLUSTER_NAME: wizfi-cluster
  REGION: us-east-1
  NAMESPACE: default

jobs:
  deploy-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        run: |
          docker build -t $DOCKER_USER/user-service:latest ./user-service
          docker push $DOCKER_USER/user-service:latest

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/user/service.yaml
